version: "3.9"

services:
  backend:
    build: .
    container_name: backend_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: node index.js
    environment:
      - NODE_ENV=development
